### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by slovvik** [sidharthkuruvila/ocaml-ide#3]
I have done all instructions, but I have no idea how to run it via Intellij Idea. It is possible?

**Comment by sidharthkuruvila** [comment]
After you run ```./gradlew buildPlugin``` do ```ls build/distributions/ocaml-idea-0.0.1-SNAPSHOT.zip```. If the file is present then you should be able to install it from the plugins dialog. You should find a button there "Install plugin from disk ...".
