### ISSUE TITLE
Error when launching IntelliJ after installing plugin

### ISSUE THREAD

**Issue by dimo414** [sidharthkuruvila/ocaml-ide#4]
I just installed this plugin (thanks, btw!) and ran into this error:

    kotlin.reflect.jvm.internal.impl.resolve.ExternalOverridabilityCondition: Provider kotlin.reflect.jvm.internal.impl.load.java.JavaIncompatibilityRulesOverridabilityCondition not a subtype

Full error: https://pastebin.com/djunQkjf

This may well be an issue with my configuration (it's a Lua+OCaml project), but I'm not sure how to investigate the issue further.

Installed Plugins:

```
Android Support (10.2.3)
Ant Support (1.0)
Bytecode Viewer (0.1)
Copyright (8.1)
Coverage (172.3968.16)
CVS Integration (11)
Eclipse Integration (3.0)
EditorConfig (172.3968.16)
Git Integration (8.1)
GitHub (172.3968.16)
Gradle (172.3968.16)
Groovy (9.0)
hg4idea (10.0)
I18n for Java (172.3968.16)
IntelliLang (8.0)
Java Bytecode Decompiler (172.3968.16)
JavaFX (1.0)
JUnit (1.0)
Kotlin (1.1.4-release-IJ2017.2-2)
Lua (1.0.109)
Markdown support (2017.2.20170419)
Maven Integration (172.3968.16)
Ocaml (0.0.1-SNAPSHOT)
Plugin DevKit (1.0)
Properties Support (172.3968.16)
Settings Repository (172.3968.16)
Subversion Integration (1.1)
Task Management (1.0)
Terminal (0.1)
TestNG-J (8.0)
UI Designer (172.3968.16)
XPathView + XSLT Support (4)
XSLT-Debugger (1.4)
YAML (172.3968.16)
```

**Comment by sidharthkuruvila** [comment]
Can you try updating the kotlin version in the file gradle.properties to 

    kotlinVersion = 1.1.51

I'll look at this later today.

**Comment by dimo414** [comment]
Yep, rebuilding and reinstalling the plugin with the updated kotlin version appears to have resolved the error. Thanks!

**Comment by sidharthkuruvila** [comment]
I'll update the version in the source repo.

I need to look into why this happens. It is possible that kotlin comes bundled with idea. In which case it might make sense to remove the kotlin jars from the plugin.
