### ISSUE TITLE
Running programs

### ISSUE THREAD

**Issue by aDogCalledSpot** [sidharthkuruvila/ocaml-ide#5]
I have the plugin installed and I can make a new OCaml project which also has correct syntax highlighting and all but I can't find a way to run the program from within the IDE.

**Comment by sidharthkuruvila** [comment]
How do you run ml scripts? I have implemented a run configuration which should work for simple scripts. It simply executes the following.

    ocamlbuild [scriptpath].native && ./scriptpath.native

You should be able to create it from the edit run configurations dialog.

It's quite limited so I don't use it myself.
